# Generated by Django 5.2.7 on 2025-11-04 07:02

import django.db.models.deletion
import uploader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=uploader.models.file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(default=0, help_text='文件大小（字节）')),
                ('file_type', models.CharField(help_text='文件类型，如zip、doc、docx', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True, null=True)),
                ('document_count', models.IntegerField(default=0, help_text='提取到的文档数量')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_part', models.CharField(blank=True, help_text='单号', max_length=100, null=True)),
                ('document_filename', models.CharField(help_text='文档文件名', max_length=255)),
                ('extraction_status', models.CharField(default='待处理', max_length=20)),
                ('extraction_error', models.TextField(blank=True, null=True)),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('terminal_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('doc_maintenance_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('overall_total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fiber_length', models.IntegerField(blank=True, help_text='光缆长度', null=True)),
                ('verification_passed', models.BooleanField(default=False)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_infos', to='uploader.uploadedfile')),
            ],
            options={
                'ordering': ['-extracted_at'],
            },
        ),
    ]
