# Generated by Django 5.2.7 on 2025-11-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedinfo',
            name='code_part',
        ),
        migrations.RemoveField(
            model_name='extractedinfo',
            name='document_filename',
        ),
        migrations.RemoveField(
            model_name='extractedinfo',
            name='fiber_length',
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='document_content',
            field=models.TextField(blank=True, help_text='从Word中提取的完整文本', null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='document_name',
            field=models.CharField(default='', help_text='文档文件名', max_length=255),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='equipment_items',
            field=models.JSONField(blank=True, help_text='设备清单', null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='fiber_info',
            field=models.JSONField(blank=True, help_text='光缆信息列表', null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, help_text='单号', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='其他费用', max_digits=10),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='verification_message',
            field=models.TextField(blank=True, help_text='验证消息', null=True),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='doc_maintenance_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='文档中维护费合计', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='维护费', max_digits=10),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='overall_total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='总体花费', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='service_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='服务费', max_digits=10),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='terminal_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='终端费', max_digits=10),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='费用总计', max_digits=10),
        ),
        migrations.AlterField(
            model_name='extractedinfo',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='总花费', max_digits=10, null=True),
        ),
        migrations.AddIndex(
            model_name='extractedinfo',
            index=models.Index(fields=['order_code'], name='uploader_ex_order_c_fafeb5_idx'),
        ),
        migrations.AddIndex(
            model_name='extractedinfo',
            index=models.Index(fields=['uploaded_file'], name='uploader_ex_uploade_75b9c8_idx'),
        ),
    ]
