# Generated by Django 5.2.8 on 2025-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0002_rename_document_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='address',
            field=models.CharField(blank=True, help_text='地址（来自ZIP文件名）', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='group_name',
            field=models.CharField(blank=True, help_text='集团名称（来自ZIP文件名）', max_length=255, null=True),
        ),
    ]
