# Generated by Django 5.2.8 on 2026-01-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0003_uploadedfile_address_uploadedfile_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='is_marked',
            field=models.BooleanField(default=False, help_text='是否标记（标星）'),
        ),
    ]
