# Generated by Django 5.2.8 on 2026-01-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0004_uploadedfile_is_marked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='is_marked',
            field=models.BooleanField(default=True, help_text='是否标记（标星）'),
        ),
    ]
