# Generated by Django 5.2.8 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0005_alter_uploadedfile_is_marked'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='township',
            field=models.CharField(blank=True, help_text='街道（高德解析，township）', max_length=255, null=True),
        ),
    ]

