# Generated by Django 5.2.8 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0006_uploadedfile_township'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='construction_unit',
            field=models.CharField(blank=True, help_text='施工单位（由街道映射）', max_length=255, null=True),
        ),
    ]

