# Generated by Django 5.2.8 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0007_uploadedfile_construction_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinfo',
            name='construction_order_code',
            field=models.CharField(blank=True, db_index=True, help_text='建设单号', max_length=100, null=True),
        ),
    ]

