# Generated by Django 5.2.8 on 2026-01-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0008_extractedinfo_construction_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinfo',
            name='construction_email_sent',
            field=models.BooleanField(default=False, help_text='是否发送建设邮件'),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='construction_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='建设邮件发送勾选时间', null=True),
        ),
    ]

