# Generated by Django 5.2.8 on 2026-03-01 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0009_extractedinfo_construction_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinfo',
            name='construction_completed_at',
            field=models.DateTimeField(blank=True, help_text='建设完成时间', null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='field_construction_at',
            field=models.DateTimeField(blank=True, help_text='现场施工时间', null=True),
        ),
        migrations.AddField(
            model_name='extractedinfo',
            name='resource_entry_at',
            field=models.DateTimeField(blank=True, help_text='资源录入时间', null=True),
        ),
        migrations.CreateModel(
            name='ConstructionRemark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='备注内容')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='uploader.extractedinfo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
