# Generated by Django 5.2.8 on 2026-03-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0010_extractedinfo_construction_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinfo',
            name='resource_address',
            field=models.CharField(blank=True, help_text='资源地址', max_length=255, null=True),
        ),
    ]
